title: Metro Kitchen Cabinets And Windows
description: Custom Kitchen Cabinets and Windows in Union Beach, NJ
theme: jekyll-theme-minimal

# Site settings
email: info@metrokitchencabinets.com
phone: (732) 566-4400
address: 1105 Union Ave, Union Beach, NJ 07735

# Business hours
hours:
  monday_friday: 9am - 6pm
  saturday: 10am - 4pm
  sunday: Closed

# Social media
social:
  facebook: "#"
  instagram: "#"
  pinterest: "#"
  houzz: "#"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 